class Timeouts:
    QR = 10
    LOGGING_IN = 45
    HEADER = 15
    ALREADY_LOGGED_IN = 5
    PINNED_CHAT = 3
    CONTACT_INFO = 3
    IMAGE_WITH_TEXT = 3
    SEND_BUTTON = 3
    PENDING_MESSAGE = 1.25
    INPUT_BOX = 5
